### ISSUE TITLE
Schema type `"string" ` for samplesheets fails validation if the input is a number

### ISSUE THREAD

**Issue by lbeltrame** [nextflow-io/nf-schema#81]
Example:

```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "master/assets/schema_input.json",
    "title": "params.input schema",
    "description": "Schema for the file provided with params.input",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "sample": {
                "type": "string",
                "pattern": ".*",
                "errorMessage": "Sample name must be provided and cannot contain spaces",
                "meta": ["id"]
            },
            "bam": {
                "type": "string",
                "format": "file-path",
                "exists": true,
                "pattern": "^\\S+\\.bam$",
                "errorMessage": "BAM file must be provided, cannot contain spaces and must have extension '.bam'"
            }
        },
        "required": ["sample", "bam"]
    }
}
```

Such a minimal samplesheet will *always* fail validation:

```
sample,bam
10091,10091-ready_filtered.bam 
```

It will only work if non-numeric characters are added to the `sample` column (e.g. `10091_`), or  if the `type` is `integer`. 

I observed this behavior with Nextflow 24.04.2 and version 2.1.1. of the nf-schema plugin.

**Comment by nvnieuwk** [comment]
Hi @lbeltrame, this is known behaviour and isn't easily fixed for CSV and TSV samplesheets. These file formats have no way of specifying the requested type so nf-schema tries to infer what type the value should be.

You however have several options to fix this issue:
1. Add the `integer` type to the schema 
2. Only use YAML or JSON samplesheets in which you can specify the type of the value
3. Specify `validation.lenientMode = true` in your configuration file. This will will enable more lenient validation of you input data (e.g. in your case it will check if the value can be successfully converted into a string type instead of checking if it is a string type)

**Comment by nvnieuwk** [comment]
Mind that option 3 will make all validation lenient, so I'd advise to use one of the first two option unless you can't do these

**Comment by nvnieuwk** [comment]
There is a note about this here: https://nextflow-io.github.io/nf-schema/latest/samplesheets/samplesheetToList/

**Comment by lbeltrame** [comment]
I've seen it, thank you. I'll close this as it's not a bug in nf-schema. Thanks for the help!
